# Generated by Django 2.2.12 on 2021-08-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctions_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('image', models.CharField(max_length=265)),
                ('start_bid', models.IntegerField()),
                ('active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_list', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
