# Generated by Django 2.2.12 on 2021-08-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
