# Generated by Django 2.2.12 on 2021-08-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions_listing',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
