# Generated by Django 2.2.12 on 2021-08-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210822_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
