# Generated by Django 2.2.12 on 2021-08-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210825_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='commentary',
        ),
    ]
