# Generated by Django 2.2.12 on 2021-08-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210829_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentary',
            new_name='comment',
        ),
    ]
